const canvas=document.querySelector('#field'),ctx=canvas.getContext('2d');let w=0,h=0,t=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)'),pointer={x:-999,y:-999};function resize(){w=canvas.clientWidth;h=canvas.clientHeight;let d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener('resize',resize);addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});function draw(){ctx.clearRect(0,0,w,h);const cx=w*.76,cy=h*.46,scale=Math.min(w*.28,370);for(let j=0;j<52;j++){for(let i=0;i<100;i++){const a=i/100*Math.PI*2,b=j/52*Math.PI*2;const r=scale*(.72+.23*Math.cos(b*3+a*2+t*.35));let x=r*Math.cos(a),y=r*Math.sin(a)*Math.sin(b),z=r*Math.sin(a)*Math.cos(b);const rot=t*.12+.3,rx=x*Math.cos(rot)+z*Math.sin(rot),rz=-x*Math.sin(rot)+z*Math.cos(rot);let px=cx+rx,py=cy+y*.92+Math.sin(a*3+t)*12;const dx=px-pointer.x,dy=py-pointer.y,dist=Math.hypot(dx,dy);if(dist<110){px+=dx*(1-dist/110)*.28;py+=dy*(1-dist/110)*.28}ctx.fillStyle=`rgba(${145+Math.round(rz/scale*35)},235,211,${.16+(rz/scale+1)*.23})`;ctx.beginPath();ctx.arc(px,py,.65+(rz/scale+1)*.45,0,Math.PI*2);ctx.fill()}}if(!reduce.matches)t+=.009;if(!document.hidden&&!reduce.matches)requestAnimationFrame(draw)}draw();document.addEventListener('visibilitychange',()=>{if(!document.hidden)draw()});reduce.addEventListener('change',draw);
const fine=matchMedia('(pointer:fine)'),cursor=document.querySelector('.cursor');let mx=0,my=0,cx=0,cy=0,cursorFrame=0;
function follow(){cx+=(mx-cx)*.22;cy+=(my-cy)*.22;cursor.style.left=cx+'px';cursor.style.top=cy+'px';if(Math.abs(mx-cx)+Math.abs(my-cy)>.2)cursorFrame=requestAnimationFrame(follow);else cursorFrame=0}
addEventListener('pointermove',e=>{if(!fine.matches||reduce.matches)return;mx=e.clientX;my=e.clientY;cursor.style.display='block';cursor.classList.toggle('active',!!e.target.closest('a,button'));if(!cursorFrame)cursorFrame=requestAnimationFrame(follow)});
document.addEventListener('pointerleave',()=>{cursor.style.display='none';pointer.x=-999;pointer.y=-999});
addEventListener('pointerdown',e=>{if(reduce.matches||!fine.matches)return;const wave=document.createElement('div');wave.className='click-wave';wave.style.left=e.clientX-6+'px';wave.style.top=e.clientY-6+'px';document.body.append(wave);wave.addEventListener('animationend',()=>wave.remove())});
if(!reduce.matches){document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
let scheduled=false;const progress=document.querySelector('.progress');function onScroll(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+'%';if(!reduce.matches)canvas.style.transform=`translateY(${Math.min(scrollY*.16,150)}px)`;scheduled=false}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(onScroll)}},{passive:true});onScroll();
addEventListener('wheel',()=>{if(!reduce.matches)t+=.035},{passive:true});
