(()=>{'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),ids=['about','research','projects'];
let deck,space,items=[],enabled=false,raf=0,start=0,total=0,h=0,entry=0,hold=0,resizeTimer;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function enable(){if(enabled||reduce.matches)return;enabled=true;document.documentElement.classList.add('chapter-mode');
space=document.createElement('div');space.className='chapter-scroll-space';space.setAttribute('aria-hidden','true');document.querySelector('#about').before(space);
deck=document.createElement('div');deck.className='chapter-deck';
items=ids.map((id,i)=>{const el=document.getElementById(id),marker=document.createComment('chapter '+id);el.before(marker);const screen=document.createElement('div');screen.className='chapter-screen';screen.style.zIndex=i+1;screen.append(el);deck.append(screen);return{id,el,screen,marker,offset:0,travel:0,length:0}});
const nav=document.createElement('nav');nav.className='chapter-pages-nav';nav.setAttribute('aria-label','内容章节');nav.innerHTML=ids.map((id,i)=>'<a href="#'+id+'">0'+(i+1)+' / '+['关于','研究','项目'][i]+'</a>').join('');deck.append(nav);
const indicator=document.createElement('div');indicator.className='chapter-position';indicator.setAttribute('aria-hidden','true');deck.append(indicator);document.body.append(deck);measure();if(ids.includes(location.hash.slice(1)))jump(location.hash.slice(1),false);}
function disable(){if(!enabled)return;enabled=false;for(const item of items){item.marker.replaceWith(item.el);item.el.style.transform='';item.el.querySelectorAll('.reveal').forEach(el=>{el.style.transform='';el.style.opacity='';delete el.dataset.offset})}deck.remove();space.remove();document.documentElement.classList.remove('chapter-mode');dispatchEvent(new Event('resize'));}
function measure(){if(!enabled)return;h=innerHeight;entry=h*.8;hold=h*.24;space.style.marginTop=-h+'px';start=space.getBoundingClientRect().top+scrollY;let offset=0;for(const item of items){item.screen.hidden=false;item.travel=Math.max(0,item.el.offsetHeight-h);item.offset=offset;item.length=entry+item.travel+hold;offset+=item.length;}total=offset+h;space.style.height=total+'px';update();}
function update(){raf=0;if(!enabled)return;const y=scrollY-start;deck.classList.toggle('is-active',y>=0&&y<total);if(y<0||y>=total){for(const item of items)item.screen.inert=true;return;}let active=0;for(let i=1;i<items.length;i++)if(y>=items[i].offset)active=i;const current=items[active],t=clamp((y-current.offset)/entry),exit=clamp((y-(total-h))/h);deck.classList.toggle('is-leaving',exit>0);
items.forEach((item,i)=>{const visible=i===active||(i===active-1&&t<1);item.screen.hidden=!visible;item.screen.inert=i!==active||t<.85||exit>0;item.screen.setAttribute('aria-hidden',String(!visible));if(!visible)return;const local=y-item.offset,scroll=clamp(local-entry,0,item.travel);item.el.style.transform='translate3d(0,'+(-scroll)+'px,0)';
if(i===0){const enter=clamp(local/entry);item.screen.style.clipPath='circle('+enter*150+'% at 50% 50%)';item.screen.style.transform='translate3d(0,'+(-exit*h)+'px,0) scale('+( .9+.1*enter)+')';item.screen.style.setProperty('--entry-glow',String(1-enter));}else{item.screen.style.clipPath='none';item.screen.style.transform='translate3d(0,'+((i===active?(1-t)*h:0)-exit*h)+'px,0)';}
item.el.querySelectorAll('.reveal').forEach((el,j)=>{const top=el.getBoundingClientRect().top-(Number(el.dataset.offset)||0);const arrival=clamp((h-top)/(h*.75)),ease=arrival*arrival*(3-2*arrival),offset=(1-ease)*55;el.dataset.offset=String(offset);el.style.opacity=String(.12+.88*ease);el.style.transform='translate3d('+((1-ease)*(j%2?18:-18))+'px,'+offset+'px,0)';});});
deck.querySelectorAll('.chapter-pages-nav a').forEach((a,i)=>{if(i===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});deck.querySelector('.chapter-position').textContent='0'+(active+1)+' / 03 · '+(y-current.offset<entry?'进入章节':y-current.offset<entry+current.travel?'向下浏览':'继续下滑 · '+(active<2?['研究','项目'][active]:'联系'));
}
function wake(){if(enabled&&!raf)raf=requestAnimationFrame(update)}
function jump(id,smooth=true){const item=items.find(x=>x.id===id);if(!enabled||!item)return;scrollTo({top:start+item.offset+entry,behavior:smooth?'smooth':'instant'});}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||!enabled||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const id=a.getAttribute('href').slice(1);if(!ids.includes(id))return;e.preventDefault();history.pushState(null,'','#'+id);jump(id);});
addEventListener('popstate',()=>{if(enabled)jump(location.hash.slice(1),false)});addEventListener('hashchange',()=>{if(enabled)jump(location.hash.slice(1),false)});
addEventListener('scroll',wake,{passive:true});addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(measure,100)});reduce.addEventListener('change',()=>reduce.matches?disable():enable());
enable();if(document.fonts)document.fonts.ready.then(measure);addEventListener('load',measure);document.querySelectorAll('img').forEach(img=>img.addEventListener('load',()=>{if(enabled)measure()}));
})();