(()=>{'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),ids=['about','research','projects'];
let deck,space,items=[],enabled=false,raf=0,start=0,total=0,h=0,entry=0,hold=0,resizeTimer,displayY=0,lastFrame=0,previousActive=-1;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=v=>{v=clamp(v);return v*v*(3-2*v)};
function enable(){if(enabled||reduce.matches)return;enabled=true;document.documentElement.classList.add('chapter-mode');
space=document.createElement('div');space.className='chapter-scroll-space';space.setAttribute('aria-hidden','true');document.querySelector('#about').before(space);
deck=document.createElement('div');deck.className='chapter-deck';
items=ids.map((id,i)=>{const el=document.getElementById(id),marker=document.createComment('chapter '+id);el.before(marker);const screen=document.createElement('div');screen.className='chapter-screen';screen.style.zIndex=i+1;screen.append(el);deck.append(screen);return{id,el,screen,marker,offset:0,travel:0,length:0,reveals:[]}});
const nav=document.createElement('nav');nav.className='chapter-pages-nav';nav.setAttribute('aria-label','内容章节');nav.innerHTML=ids.map((id,i)=>'<a href="#'+id+'"><span>0'+(i+1)+' / '+['关于','研究','项目'][i]+'</span><i aria-hidden="true"></i></a>').join('');deck.append(nav);
const indicator=document.createElement('div');indicator.className='chapter-position';indicator.setAttribute('aria-hidden','true');deck.append(indicator);document.body.append(deck);measure();if(ids.includes(location.hash.slice(1)))jump(location.hash.slice(1),false);}
function disable(){if(!enabled)return;enabled=false;cancelAnimationFrame(raf);raf=0;previousActive=-1;for(const item of items){item.marker.replaceWith(item.el);item.el.style.transform='';item.el.querySelectorAll('.reveal').forEach(el=>{el.style.transform='';el.style.opacity='';delete el.dataset.offset})}deck.remove();space.remove();document.documentElement.classList.remove('chapter-mode');dispatchEvent(new Event('resize'));}
function measure(){if(!enabled)return;h=innerHeight;entry=h*.8;hold=h*.24;space.style.marginTop=-h+'px';start=space.getBoundingClientRect().top+scrollY;let offset=0;for(const item of items){item.screen.hidden=false;item.screen.style.transform='none';item.el.style.transform='none';const elements=[...item.el.querySelectorAll('.reveal')];elements.forEach(el=>{el.style.transform='none';el.dataset.offset='0'});const base=item.el.getBoundingClientRect().top;item.reveals=elements.map((el,i)=>({el,i,top:el.getBoundingClientRect().top-base}));item.travel=Math.max(0,item.el.offsetHeight-h);item.offset=offset;item.length=entry+item.travel+hold;offset+=item.length;}total=offset+h;space.style.height=total+'px';displayY=scrollY-start;lastFrame=0;wake();}
function update(now){raf=0;if(!enabled)return;const targetY=scrollY-start,dt=Math.min(48,now-(lastFrame||now-16));lastFrame=now;const tau=matchMedia('(pointer:coarse)').matches?40:75;displayY+=(targetY-displayY)*(1-Math.exp(-dt/tau));if(Math.abs(targetY-displayY)<.15)displayY=targetY;const y=displayY;deck.classList.toggle('is-active',y>=0&&y<total);if(y<0||y>=total){for(const item of items){item.screen.inert=true;item.el.querySelectorAll('video').forEach(v=>{if(!v.paused)v.pause()});}if(y!==targetY)wake();return;}let active=0;for(let i=1;i<items.length;i++)if(y>=items[i].offset)active=i;const current=items[active],t=clamp((y-current.offset)/entry),e=ease(t),exit=clamp((y-(total-h))/h);deck.classList.toggle('is-leaving',exit>0);deck.style.setProperty('--chrome-opacity',String(ease(y/(entry*.65))*(1-ease(exit*3))));
if(previousActive!==active){items.forEach((item,i)=>{if(i!==active)item.el.querySelectorAll('video').forEach(v=>{if(!v.paused)v.pause()})});previousActive=active;}
items.forEach((item,i)=>{const visible=i===active||(i===active-1&&t<1);item.screen.hidden=!visible;item.screen.inert=i!==active||t<.98||exit>0;item.screen.setAttribute('aria-hidden',String(i!==active));if(!visible)return;const local=y-item.offset,scroll=clamp(local-entry,0,item.travel),enter=ease(local/entry),screenY=(i===active&&i>0?(1-e)*h:0)-exit*h;item.el.style.transform='translate3d(0,'+(-scroll)+'px,0)';item.screen.style.borderRadius=i===active&&i>0?((1-e)*22)+'px '+((1-e)*22)+'px 0 0':'0';item.screen.style.setProperty('--edge-alpha',String(i===active?1-e:0));item.screen.style.filter=i<active?'brightness('+(1-.2*e)+')':'none';
if(i===0){item.screen.style.clipPath=enter>=1?'none':'circle('+enter*74+'% at 50% 50%)';item.screen.style.transform='translate3d(0,'+screenY+'px,0) scale('+( .96+.04*enter)+')';item.screen.style.setProperty('--entry-glow',String(1-enter));}else{item.screen.style.clipPath='none';item.screen.style.transform='translate3d(0,'+screenY+'px,0)';}
item.reveals.forEach(({el,i:j,top})=>{const arrival=clamp((h-(top-scroll))/(h*.8)),v=ease(arrival),offset=(1-v)*36;el.dataset.offset=String(offset);el.style.opacity=String(.08+.92*v);el.style.transform='translate3d(0,'+offset+'px,0)';});});
const reading=clamp((y-current.offset-entry)/Math.max(1,current.travel));deck.querySelectorAll('.chapter-pages-nav a').forEach((a,i)=>{if(i===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');a.style.setProperty('--read',String(i<active?1:i===active?reading:0))});deck.querySelector('.chapter-position').textContent='0'+(active+1)+' / 03 · '+(y-current.offset<entry?'进入章节':y-current.offset<entry+current.travel?'向下浏览 ↓':'继续下滑 · '+(active<2?['研究','项目'][active]:'联系'));
if(y!==targetY)wake();
}
function wake(){if(enabled&&!raf)raf=requestAnimationFrame(update)}
function jump(id,smooth=true){const item=items.find(x=>x.id===id);if(!enabled||!item)return;const top=start+item.offset+entry;if(!smooth){displayY=top-start;lastFrame=0;}scrollTo({top,behavior:smooth?'smooth':'instant'});wake();}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||!enabled||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const id=a.getAttribute('href').slice(1);if(!ids.includes(id))return;e.preventDefault();history.pushState(null,'','#'+id);jump(id);});
addEventListener('popstate',()=>{if(enabled)jump(location.hash.slice(1),false)});addEventListener('hashchange',()=>{if(enabled)jump(location.hash.slice(1),false)});
addEventListener('scroll',wake,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){items.forEach(item=>item.el.querySelectorAll('video').forEach(v=>v.pause()))}else wake()});addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(measure,100)});reduce.addEventListener('change',()=>reduce.matches?disable():enable());
enable();if(document.fonts)document.fonts.ready.then(measure);addEventListener('load',measure);document.querySelectorAll('img').forEach(img=>img.addEventListener('load',()=>{if(enabled)measure()}));
})();